services:
  postgres:
    image: postgres:17-alpine
    container_name: jitterbit_pg
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: jitterbit
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
